workflows:
  ios:
    name: Build iOS App
    max_build_duration: 60 # Max duration for the build (in minutes)

    environment:
      flutter: stable  # Use the stable Flutter channel

    scripts:
      - flutter doctor  # Check Flutter setup
      - flutter pub get  # Install dependencies

    build:
      ios:
        build_mode: release  # Build in release mode
        target: lib/main.dart  # Main entry Dart file

    artifacts:
      - build/ios/iphoneos/*.ipa  # Upload the IPA file after the build

